// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package git_mocks

import (
	"github.com/adamkirk/orca/internal/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextResolver creates a new instance of MockContextResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextResolver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockContextResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockContextResolver is an autogenerated mock type for the contextResolver type
type MockContextResolver struct {
	mock.Mock
}

type MockContextResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextResolver) EXPECT() *MockContextResolver_Expecter {
	return &MockContextResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockContextResolver
func (_mock *MockContextResolver) Resolve(ws string, project string) (common.ExecutionContext, error) {
	ret := _mock.Called(ws, project)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 common.ExecutionContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (common.ExecutionContext, error)); ok {
		return returnFunc(ws, project)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) common.ExecutionContext); ok {
		r0 = returnFunc(ws, project)
	} else {
		r0 = ret.Get(0).(common.ExecutionContext)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(ws, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockContextResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ws string
//   - project string
func (_e *MockContextResolver_Expecter) Resolve(ws any, project any) *MockContextResolver_Resolve_Call {
	return &MockContextResolver_Resolve_Call{Call: _e.mock.On("Resolve", ws, project)}
}

func (_c *MockContextResolver_Resolve_Call) Run(run func(ws string, project string)) *MockContextResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextResolver_Resolve_Call) Return(executionContext common.ExecutionContext, err error) *MockContextResolver_Resolve_Call {
	_c.Call.Return(executionContext, err)
	return _c
}

func (_c *MockContextResolver_Resolve_Call) RunAndReturn(run func(ws string, project string) (common.ExecutionContext, error)) *MockContextResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
